# Generated by Django 3.2.3 on 2021-06-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_contacts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='relation',
            field=models.CharField(default='no relation', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
